# Generated by Django 2.2.6 on 2020-01-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_type', models.TextField(verbose_name='Race Type')),
                ('race_available', models.BooleanField(default=False, verbose_name='Available')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.CharField(max_length=100, verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='WinnerPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='event.Player')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='event.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Player')),
            ],
        ),
    ]
